search_api.backend.plugin.search_api_solr_multilingual:
  type: search_api.backend.plugin.search_api_solr
  label: 'Search API Multilingual Solr settings'

search_api.backend.plugin.search_api_solr_multilingual_managed_schema:
  type: search_api.backend.plugin.search_api_solr_multilingual
  label: 'Search API Multilingual Solr Managed Schema settings'
