apachesolr_multilingual.solr_field_type.*:
  type: config_entity
  label: 'Solr Field Type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    field_type:
      type: mapping
      label: 'Field Type'
    text_files:
      type: mapping
      label: 'Text Files'
