apachesolr_multilingual.asm_text_field_filter.*:
  type: config_entity
  label: 'TextFieldFilterFilter config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
